mae_demo/googleauth/authentication/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


app_name = 'authentication'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_profile', views.create_profile, name='create_profile'),
    path('profile', views.view_profile, name='view_profile'),
    path('edit_profile_name', views.edit_profile, {'item': 'name'}, name='edit_profile_name'),
    path('edit_profile_image', views.edit_profile, {'item': 'image'}, name='edit_profile_image'),
    path('edit_profile_email', views.edit_profile, {'item': 'email'}, name='edit_profile_email'),
    path('edit_profile_age', views.edit_profile, {'item': 'age'}, name='edit_profile_age'),
    path('edit_profile_gender', views.edit_profile, {'item': 'gender'}, name='edit_profile_gender'),
    path('edit_profile_interest', views.edit_profile, {'item': 'interest'}, name='edit_profile_interest'),
    path('about', views.about, name='about')
]

mae_demo/googleauth/event/urls.py
from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('index', views.event_index, name='event_index'),
    path('create_event', views.create_event, name='create_event'),
    path('update_participants/<int:event_id>', views.update_participants, name='update_participants')
] 

mae_demo/googleauth/googleauth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    # path('', TemplateView.as_view(template_name="login/index.html")),
    path('accounts/', include('allauth.urls')),
    path('', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mae_demo/googleauth/event/models.py
from django.db import models

# Create your models here.
from authentication.models import SparkUser

# Not used.. But I don't know how to get rid of this. 
# Deleting this will cause errors. 
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'data/{0}/{1}'.format(instance.id, filename)


class Event(models.Model):
    name = models.CharField(max_length=50)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location = models.CharField(max_length=30)
    image = models.FileField(upload_to='images/',
                             default='data/jisungpark1.jpg')
    participants = models.ManyToManyField(SparkUser)

mae_demo/googleauth/event/forms.py
from django import forms
from django.contrib.admin import widgets
import datetime


class EventCreateForm(forms.Form):
    name = forms.CharField(label='Event Name', max_length=100,
                            widget = forms.TextInput(
                            attrs = {'style': 'width: 30%; height:35px; border-radius: 5px'
                                    }
                        ))
    location = forms.CharField(label='Event Location', max_length=100,
                                widget = forms.TextInput(
                                attrs = {'style': 'width: 30%; height:35px; border-radius: 5px'
                                        }
                            ))
    start_time = forms.SplitDateTimeField(label='Start Time', 
                            widget=widgets.AdminSplitDateTime(
                            attrs = {'style': 'width: 30%; height:35px; border-radius: 5px'
                                    }
                        ))
    end_time = forms.SplitDateTimeField(label='End Time', 
                            widget=widgets.AdminSplitDateTime(                            
                            attrs = {'style': 'width: 30%; height:35px; border-radius: 5px'
                                                    }
                                        ))
    image = forms.ImageField(label="Image")

mae_demo/googleauth/event/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from .models import Event
from .forms import EventCreateForm
from authentication.models import SparkUser


def event_index(request):
    sparkuser = SparkUser.objects.get(user=request.user)
    event_list = Event.objects.all()
    context = {'event_list': event_list, 'rsvped_event_list': sparkuser.event_set.all()}
    return render(request, 'event/event_index.html', context)


def create_event(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print("form post request done")
        form = EventCreateForm(request.POST, request.FILES or None)
        # check whether it's valid:
        print("form. is_valid done")
        if form.is_valid():
            # Grab the form data
            print("1st field done")
            name = form.cleaned_data['name']
            print("2nd field done")
            loc = form.cleaned_data['location']
            print("3rd field done")
            s_time = form.cleaned_data['start_time']
            print("4th field done")
            e_time = form.cleaned_data['end_time']
            image = form.cleaned_data['image']

            # Create and save a new event object
            e = Event(name=name, start_time=s_time,
                      end_time=e_time, location=loc, image=image)
            e.save()

        # Filled the form out incorrectly..
        else:
            for k in form.errors:
                print(k + form.errors[k])
            request.method = "GET"
            return create_event(request)

        # Redirect user to see all the events.
        return event_index(request)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = EventCreateForm()

    return render(request, 'event/event_form.html', {'form': form})

# Called when Going/Not Going button is clicked on the Event page.
def update_participants(request, event_id):
    s = SparkUser.objects.get(user=request.user)
    e = Event.objects.get(id=event_id)
    if e in s.event_set.all():
        e.participants.remove(s)
    else:    
        e.participants.add(s)
    e.save()
    # CHANGE WHEN DEPLOYING! 
    return redirect('http://127.0.0.1:8000/event/index')

mae_demo/googleauth/event/templates/event/event_form.html
<!DOCTYPE html>
<html lang="en">
{%load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wellness Abroad | Event</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">
</head>

<body>

  <!-- Start Navigation -->

  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark fixed-top">
    <!--         <div class="container-fluid">
--> <a class="navbar-brand" href="{% url 'authentication:index' %}">
      <img src="{% static 'authentication/logo.png' %}">
      Wellness Abroad</a>
    <!-- Start Button -->

    <button class="navbar-toggler" type="button " data-toggle="collapse" data-target="#navbarResponsive">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Start Button -->

    <button class="navbar-toggler navbar-toggler-right" type="button " data-toggle="collapse"
      data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- End Button -->

    <!-- Start Links -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <!-- Home -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:index' %}">Home</a>
        </li>

        <!-- About -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:about' %}">About</a>
        </li>

        <!-- Profile -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:view_profile' %}">Profile</a>
        </li>

        <!-- Events -->
        <li class="nav-item">
          <a style="color: white" class="nav-link" href="{% url 'event:event_index' %}">Events</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
        </li>

      </ul>
    </div>
    <!-- End Links-->


    </div>
    <!-- End Container -->
  </nav>

  <!-- End Navigation -->
  <div style="height: 80px"> </div>

  <!-- Start Contianer -->
  <div class="container">

    <!-- Contact Form -->
    <h3 style="font-size: 40px"> New Event </h3>

    {% for field in form %}
    <div style="height: 25px"> </div>
    <div>
      <form enctype="multipart/form-data" action="create_event" method="post">
        {% csrf_token %}
        {{field.label}}
        {% if field.label == 'Start Time' %}
        <p style="color: gray; font-size: 0.8rem"> Date = 2019-05-06, Time = 13:25:00 </p>
        {% endif %}
        {% if field.label == 'End Time' %}
        <p style="color: gray; font-size: 0.8rem"> Date = 2019-05-06, Time = 13:25:00 </p>
        {% endif %}
        {{ field }}
        {%endfor%}
        <div style="height: 30px"></div>
        <input type="submit" value="Submit">
      </form>


      <!-- <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group form-group">
            <div class="controls">
              </label>Name: </label>
              <input type="text" class="form-control" id="name" required
                date-validation-required-message="Please enter the name of the event">
              <p class="help-block"></p>
            </div>
          </div>

          <div class="control-group form-group">
            <div class="controls">
              </label>Start Time: </label>
              <input type="text" class="form-control" id="name" required
                date-validation-required-message="Please enter the start time">
              <p class="help-block"></p>
            </div>
          </div>

          <div class="control-group form-group">
            <div class="controls">
              </label>End Time: </label>
              <input type="text" class="form-control" id="name" required
                date-validation-required-message="Please enter the end time">
              <p class="help-block"></p>
            </div>
          </div>

          <div class="control-group form-group">
            <div class="controls">
              </label>Location: </label>
              <input type="text" class="form-control" id="name" required
                date-validation-required-message="Please enter the location">
              <p class="help-block"></p>
            </div>
          </div>

          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Create</button>

        </form> -->
    </div>
  </div>


  </div>
  <!--End Container-->
  <div style="height: 60px"> </div>

  <br>
  <br>

  <!-- Footer -->
  <footer class="py-5 bg-dark"
    style="background-color: #073949!important; position:absolute; width: 100%; bottom: -50px; height: 30px; left: 0px; right: 0px;">
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script type="text/javascript" src="/media/admin/js/core.js"></script>

  <link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />
  <link rel="stylesheet" type="text/css" href="/media/admin/css/base.css" />
  <link rel="stylesheet" type="text/css" href="/media/admin/css/global.css" />
  <link rel="stylesheet" type="text/css" href="/media/admin/css/widgets.css" />
</body>

</html>

mae_demo/googleauth/event/templates/event/event_index.html
<!doctype html>
<html lang="en">

{%load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wellness Abroad | Event</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'event/style.css' %}">
</head>


<body>

  <!-- Start Navigation -->

  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark fixed-top">
    <!--         <div class="container-fluid">
--> <a class="navbar-brand" href="{% url 'authentication:index' %}">
      <img src="{% static 'authentication/logo.png' %}">
      Wellness Abroad</a>
    <!-- Start Button -->
    <!-- Start Button -->

    <button class="navbar-toggler navbar-toggler-right" type="button " data-toggle="collapse"
      data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- End Button -->

    <!-- Start Links -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <!-- Home -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:index' %}">Home</a>
        </li>

        <!-- About -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:about' %}">About</a>
        </li>

        <!-- Profile -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:view_profile' %}">Profile</a>
        </li>

        <!-- Events -->
        <li class="nav-item">
          <a style="color: white" class="nav-link" href="{% url 'event:event_index' %}">Events</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
        </li>

      </ul>
    </div>
    <!-- End Links-->


    </div>
    <!-- End Container -->
  </nav>

  <!-- End Navigation -->
  <div style="height: 58px"> </div>
  <!-- Start Contianer -->

  <!-- Start Breadcrumb -->
  <div class="sticky-top">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Events</li>
      <li class="breadcrumb-item active"><a href="{% url 'event:create_event' %}"> Create Event </a></li>
    </ol>
  </div>
  <!--End Breadcrumb-->
  <div class="container">

    {% if event_list %}

    {% for event in event_list %}

    <div class=" row">

      <div class="col-md-7">
        <!-- <img src="{% static "my_app/example.jpg" %}" alt="My image"> -->
        <img style="width: 500px; height: 300px" class="img-fluid rounded mb-3 mb-md-0" src="{{ event.image.url }}"
          alt="My Image">
      </div>
      <div class="col-md-5">
        <h3>{{event.name}}</h3>
        <div style="height:5px"> </div>
        <p style="font-size: 20px">start: {{event.start_time}}</p>
        <div style="height:3px"> </div>
        <p style="font-size: 20px">end: {{event.end_time}}</p>
        <div style="height:3px"> </div>
        <p style="font-size: 20px">location: {{event.location}}</p>
        {% if event in rsvped_event_list %}
        <a class="btn btn-primary" href="{% url 'event:update_participants' event.id %}">Not Going
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'event:update_participants' event.id %}">Going
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
        {% endif %}
      </div>

    </div>

    {% endfor %}

    {% else %}
    <!-- <p>No polls are available.</p> -->
    {% endif %}

  </div>
  <!--End Container-->

  <br>
  <br>


  <!-- Footer -->
  <footer class="py-5 bg-dark"
    style="background-color: #073949!important; position:absolute; width: 100%; bottom: -50px; height: 30px">
  </footer>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>