mae_demo/googleauth/authentication/urls.py
from django.conf.urls import url
from django.urls import path

from . import views


app_name = 'authentication'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_profile', views.create_profile, name='create_profile'),
    path('profile', views.view_profile, name='view_profile'),
    path('edit_profile_name', views.edit_profile, {'item': 'name'}, name='edit_profile_name'),
    path('edit_profile_image', views.edit_profile, {'item': 'image'}, name='edit_profile_image'),
    path('edit_profile_email', views.edit_profile, {'item': 'email'}, name='edit_profile_email'),
    path('edit_profile_age', views.edit_profile, {'item': 'age'}, name='edit_profile_age'),
    path('edit_profile_gender', views.edit_profile, {'item': 'gender'}, name='edit_profile_gender'),
    path('edit_profile_interest', views.edit_profile, {'item': 'interest'}, name='edit_profile_interest'),
    path('about', views.about, name='about')
]

mae_demo/googleauth/event/urls.py
from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('index', views.event_index, name='event_index'),
    path('create_event', views.create_event, name='create_event'),
    path('update_participants/<int:event_id>', views.update_participants, name='update_participants')
] 

mae_demo/googleauth/googleauth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    # path('', TemplateView.as_view(template_name="login/index.html")),
    path('accounts/', include('allauth.urls')),
    path('', include('authentication.urls')),
    path('event/', include('event.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mae_demo/googleauth/authentication/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class SparkUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # This field is just to check that this user has filled out their profiles.
    profile_filled = models.BooleanField(default=False)
    # Relevant Fields..
    name = models.CharField(max_length=100, default="No Name")
    image = models.ImageField(upload_to='images/',
                             default='data/jisungpark1.jpg')
    email = models.CharField(max_length=100, default = "No Emails")
    age = models.IntegerField()
    gender = models.CharField(max_length=30)
    interest = models.CharField(max_length=150, default = "No interest")

mae_demo/googleauth/authentication/forms.py
from django import forms
from django.contrib.admin import widgets
import datetime


class ProfileForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100,
    						widget = forms.TextInput(
           					attrs = {'style': 'width: 30%; height:30px; border-radius: 5px'
                					 }
        					))
    image = forms.ImageField(label="Image")
    email = forms.CharField(label= "Email",
							widget = forms.TextInput(
			           		attrs = {'style': 'width: 30%; height:30px; border-radius: 5px'
			             			}
						))
    age =forms.CharField(label= "Age",
							widget = forms.TextInput(
			           		attrs = {'style': 'width: 30%; height:30x; border-radius: 5px'
			                		}
						))

    gender = forms.CharField(label="Gender",widget = forms.TextInput(
			           		attrs = {'style': 'width: 30%; height:30px; border-radius: 5px'
			                			}
						))
    interest =  forms.CharField(label="Interest",
							widget = forms.TextInput(
			           		attrs = {'style': 'width: 30%; height:30px; border-radius: 5px'
			                			}
						))

class ProfileNameForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100,
    						widget = forms.TextInput(
           					attrs = {'style': 'width: 60%; height:45px; border-radius: 10px'
                					}
        					))

class ProfileImageForm(forms.Form):
    image = forms.ImageField(label="Image")

class ProfileEmailForm (forms.Form): 
	email = forms.CharField(label= "Email",
							widget = forms.TextInput(
			           		attrs = {'style': 'width: 60%; height:45px; border-radius: 10px',
			                			'placeholder': 'This Field is Required'}
						))

class ProfileAgeForm(forms.Form):
    age = forms.IntegerField(label="Age",  
    						widget = forms.TextInput(
			           		attrs = {'style': 'width: 60%; height:45px; border-radius: 10px',
			                			'placeholder': 'This Field is Required'}
						))

class ProfileGenderForm(forms.Form):
    gender = forms.CharField(label="Gender",widget = forms.TextInput(
			           		attrs = {'style': 'width: 60%; height:45px; border-radius: 10px',
			                			'placeholder': 'This Field is Required'}
						))


class ProfileInterestForm (forms.Form): 
	interest = forms.CharField(label="Interest",
							widget = forms.TextInput(
			           		attrs = {'style': 'width: 60%; height:45px; border-radius: 10px',
			                			'placeholder': 'This Field is Required'}
						))

mae_demo/googleauth/authentication/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import SparkUser
from .forms import ProfileForm, ProfileAgeForm, ProfileNameForm, ProfileEmailForm, ProfileGenderForm, ProfileImageForm, ProfileInterestForm
from django.contrib import messages

def index(request):
    if request.user.is_authenticated:
        try:
            sparkuser = SparkUser.objects.get(user=request.user)
            print("the spark user is not yet created for this user.")

        except:
            sparkuser = SparkUser(user=request.user, profile_filled=False, email="null", age=100, gender="neutral")
            sparkuser.save()
            print("the spark user is now created for this user.")

        finally:
            sparkuser = SparkUser.objects.get(user=request.user)
            if sparkuser.profile_filled:
                return render(request, 'authentication/home.html')
            else:
                return create_profile(request)
    else:
        return render(request, 'authentication/index.html')


def create_profile(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ProfileForm(request.POST, request.FILES or None)
        # check whether it's valid:
        if form.is_valid():
            # Grab the form data
            name = form.cleaned_data['name']
            image = form.cleaned_data['image']
            email = form.cleaned_data['email']
            age = form.cleaned_data['age']
            gender = form.cleaned_data['gender']
            interest = form.cleaned_data['interest']

            # Create and save a new event object
            sparkuser = SparkUser.objects.get(user=request.user)
            sparkuser.name = name
            sparkuser.image = image
            sparkuser.email = email
            sparkuser.age = age
            sparkuser.gender = gender 
            sparkuser.interest = interest
            sparkuser.profile_filled = True
            try: 
                sparkuser.save(update_fields=["name", "profile_filled",\
                'image', 'email', 'age','gender', 'interest'])
            except:
                messages.error(request, 'Please fill the profile fully and correctly!')
                request.method = "GET"
                return create_profile(request)

        # Filled the form out incorrectly..
        else:
            for k in form.errors:
                print(k + form.errors[k])
            request.method = "GET"
            return create_profile(request)

        # Redirect user to the homepage!
        return index(request)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProfileForm()

    return render(request, 'authentication/profile_form.html', {'form': form})


def view_profile(request):
    profile = SparkUser.objects.get(user_id=request.user.id)
    context = {'user': profile}
    return render(request, 'authentication/profile.html', context)

def edit_profile(request, item):
    print(item)
    # Get the current user 
    sparkuser = SparkUser.objects.get(user=request.user)

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        if item == "name":
            print ('name form!')
            form = ProfileNameForm(request.POST or None)
        elif item == 'email': 
            print ('email form!')
            form = ProfileEmailForm(request.POST or None)
        elif item == 'age':
            print ('age form!')
            form = ProfileAgeForm(request.POST or None)
        elif item == 'gender':
            print ('gender form!')
            form = ProfileGenderForm(request.POST or None)
        elif item == "interest": 
            print ('interest form!')
            form = ProfileInterestForm(request.POST or None)
        else: # image!
            print ('image form!')
            form = ProfileImageForm(request.POST, request.FILES or None)
        # check whether it's valid:
        if form.is_valid():
            # Grab the form data
            new = form.cleaned_data[item]

            # Update the sparkuser object
            if item == "name":
                sparkuser.name = new
                sparkuser.save(update_fields=["name"])
            elif item == 'email':
                sparkuser.email = new
                sparkuser.save(update_fields=['email'])
            elif item == 'age':
                sparkuser.age = new
                sparkuser.save(update_fields=['age'])
            elif item == 'gender':
                sparkuser.gender = new 
                sparkuser.save(update_fields=['gender'])
            elif item == 'interest': 
                sparkuser.interest = new
                sparkuser.save(update_fields=['interest'])
            else: # Image!
                sparkuser.image = new
                sparkuser.save(update_fields=['image'])

        # Filled the form out incorrectly..
        else:
            for k in form.errors:
                print(k + form.errors[k])
            request.method = "GET"
            return edit_profile(request, item)

        # Redirect user to the homepage!
        return view_profile(request)

    # if a GET (or any other method) we'll create a blank form
    else:
        if item == "name":
            form = ProfileNameForm(request.POST)
        elif item == 'email': 
            form = ProfileEmailForm(request.POST)
        elif item == 'age':
            form = ProfileAgeForm(request.POST)
        elif item == 'gender':
            form = ProfileGenderForm(request.POST)
        elif item == 'interest': 
            form = ProfileInterestForm(request.POST)
        else: #image!
            form = ProfileImageForm(request.POST, request.FILES or None)

    return render(request, 'authentication/edit_profile.html', {'form': form, 'item':item, 'user':sparkuser})


def about(request):
    return render(request, 'authentication/about.html')

mae_demo/googleauth/authentication/templates/authentication/about.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

{% load socialaccount %}

{% providers_media_js %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wellness Abroad | About</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <!-- <link href="style.css" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'authentication/style.css' %}">

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark fixed-top">
        <!--         <div class="container-fluid">
 --> <a class="navbar-brand" href="{% url 'authentication:index' %}">
            <img src="{% static 'authentication/logo.png' %}">
            Wellness Abroad</a>

        <button class="navbar-toggler" type="button " data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <!-- Home -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:index' %}">Home</a>
                </li>

                <!-- About -->
                <li class="nav-item">
                    <a style="color: white" class="nav-link" href="{% url 'authentication:about' %}">About</a>
                </li>

                {% if user.is_authenticated %}
                <!-- Profile -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:view_profile' %}">Profile</a>
                </li>

                <!-- Events -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'event:event_index' %}">Events</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% provider_login_url 'google' %}">Log In</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% provider_login_url 'google' %}">Sign Up</a>
                </li>

                {% endif %}
            </ul>
            <!-- </div> -->
            <!-- End Links-->
        </div>
        <!-- End Container -->
    </nav>
    <!-- End Navigation -->
    <div style="height: 100px"> </div>
    <!-- Start Contianer -->
    <div class="container">

        <!-- Page Title -->
        <div class="container">
            <!-- <div height: 150% > </div> -->
            <h1 class="mt-4 mb-10" style="text-align: center"> About Us </h1>

            <!-- Start Breadcrumb -->
            <!--   <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html">Home</a>
            </li>
            <li class="breadcrumb-item active">About</li>
        </ol> -->
            <!--End Breadcrumb-->
            <div style="height: 100px"> </div>

            <!-- Start Row-->
            <div class="row">
                <div style="height: 50px"></div>

                <div class="col-lg-6">
                    <img height="350px" width="450px" src="{% static 'authentication/diagram.jpg' %}">
                </div>
                <!-- <div style = "height: 100px">  </div> -->

                <div class="col-lg-6">

                    <p> According to the user research we conducted, the majority of international students feel
                        a severe sense of isolation and loneliness because they tend to not have an intimate
                        community in the U.S. Unfortunately, international students are observed to be more reluctant
                        to seek help due to the lack of cultural familiarity and different emotional norms that support
                        the mental problem (Pupavac, 2004). Therefore, international students are relatively more
                        prone to risks of depression and other mental health problems.
                        We aim to support international students by providing a platform that could aid in
                        improving their mental health. Wellness Abroad generates connections between the students
                        and local hosts to help increase the students’ sense of belonging in a foreign country.
                    </p>

                </div>
            </div>

        </div>

    </div>
    <!--End Container-->

    <br>
    <br>


    <!-- Footer -->

    <!--  nned to change it so it is stuck into the bottom of the page -->
    <footer class="py-5 bg-dark"
        style="background-color: #073949!important; position:absolute; width: 100%; bottom: -50px; height: 30px">
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

mae_demo/googleauth/authentication/templates/authentication/home.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

{% load socialaccount %}

{% providers_media_js %}

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Wellness Abroad | Main</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'authentication/style.css' %}">
</head>



<body>
	<!-- Start Home Section-->
	<div id="home">
		<!-- Navigation -->
		<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			<a class="navbar-brand" href="{% url 'authentication:index' %}">
				<img src="{% static 'authentication/logo.png' %}"> Wellness Abroad</a>

			<button class="navbar-toggler" type="button " data-toggle="collapse" data-target="#navbarResponsive">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<!-- Home -->
					<li class="nav-item">
						<a style="color: white" class="nav-link" href="{% url 'authentication:index' %}">Home</a>
					</li>

					<!-- About -->
					<li class="nav-item">
						<a class="nav-link" href="{% url 'authentication:about' %}">About</a>
					</li>

					<!-- Profile -->
					<li class="nav-item">
						<a class="nav-link" href="{% url 'authentication:view_profile' %}">Profile</a>
					</li>

					<!-- Events -->
					<li class="nav-item">
						<a class="nav-link" href="{% url 'event:event_index' %}">Events</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
					</li>

				</ul>
			</div>
			<!-- End Links-->


		</nav>
		<!-- End Container -->
	</div>

	<!-- End Navigation -->

	<!--- Image Slider -->
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="7000">
		<ol class="carousel-indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<!-- Slide 1 -->
			<div class="carousel-item active">
				<img style="width: 100%" src="{% static 'authentication/first.png' %}">
				<div class="carousel-caption text-center">
					<h1 class="display-2">We believe in Community</h1>
					<h3 style="font-size: 20px; color:white">We will help students by connecting with local hosts who will become
						their close
						community.</h3>
					<!-- 		<a class="btn btn-outline-light btn-lg" href="profile.html">Get Started
					</a> -->
				</div>
			</div>
			<!-- Slide 2 -->
			<div class="carousel-item">
				<img style="width: 100%" src="{% static 'authentication/second.png' %}">
			</div>
			<!-- Slide 3 -->
			<div class="carousel-item">
				<img style="width: 100%" src="{% static 'authentication/third.png' %}">
			</div>
		</div>

		<!-- Start Previous -->
		<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<!-- End Previous-->

		<!-- Start Next -->
		<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
		<!-- End Next-->
	</div>
	<!-- End Carousel Div -->
	<!--- Two Column Section -->
	<div class="container-fluid padding">
		<div class="row text-center padding">
			<div class="col-lg-6">
				<h2>Benefits for building a community</h2>
				<p>
					The need for connection and community is primal, as fundamental as the need for air, water,
					and food.
					- Dean Ornish</p>
				<br>
				<a href="{% url 'authentication:about' %}" class="btn btn-primary">Learn More</a>
			</div>
			<div class="col-lg-6">
				<img src="{% static 'authentication/small.png' %}" class="img-fluid">
			</div>
		</div>
	</div>
	<br>
	<br>
	<br>
	<hr class="my-4">
	<br>
	<!--- Welcome Section -->
	<div class="container-fluid padding">
		<div class="row welcome text-center">
			<div class="col-12">
				<h1 class="display-4">Event</h1>
			</div>
			<hr>
			<div class="col-12">
				<!-- 			<p class="lead">Lorem ipsum dolor sit amet,
					consectetur adipiscing elit. Quid nunc honeste dicit?
					Non quam nostram quidem, inquit Pomponius iocans; Introduci
					enim virtus nullo modo potest, nisi omnia, quae leget quaeque.</p> -->
			</div>
		</div>
	</div>
	<br>
	<br>

	<!--- Three Column Section -->
	<div class="container-fluid padding">
		<div class="row text-center padding">
			<div class="col-md-4">
				<div class="Card">
					<h4 class="card-title">Want to host an event?</h4>
					<br>
					<img class="card-imd-top" src="{% static 'authentication/fi.png' %}">
					<div class="card-body">
						<p class="card-text">All you need is 5 minutes to register your event.
							Fill our information. Publish the event.</p>
						<a href="{% url 'event:create_event' %}" class="btn btn-primary">REGISTER YOUR EVENT</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="Card">
					<h4 class="card-title">Become a Host</h4>
					<br>
					<img class="card-imd-top" src="{% static 'authentication/si.png' %}">
					<div class="card-body">
						<p class="card-text">Are you willing to be a host but not sure how?
							This is the guide that will help you begin.</p>
						<a href="{% static 'authentication/eventhostguide.pdf' %}" class="btn btn-primary">DOWNLOAD PDF</a>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="Card">
					<h4 class="card-title">Become a Host</h4>
					<br>
					<img class="card-imd-top" src="{% static 'authentication/ti.png' %}">
					<div class="card-body">
						<p class="card-text">Try out for an opportunity to expand your
							social circle. Gain lasting friends.</p>
						<a href="{% url 'event:event_index' %}" class="btn btn-primary">SEARCH YOUR EVENT</a>
					</div>
				</div>
			</div>

		</div>
	</div>
	<br>

	<br>
	<br>
	<!-- Footer -->
	<footer class="py-5 bg-dark"
		style="background-color: #073949!important; position:absolute; width: 100%; bottom: -50px; height: 30px">
	</footer>
</body>

</html>

mae_demo/googleauth/authentication/templates/authentication/profile.html
<!DOCTYPE html>
<html lang="en">
{%load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wellness Abroad | Profile</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'authentication/style.css' %}">
</head>

<body>

  <!-- Start Navigation -->

  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark fixed-top">
    <!--         <div class="container-fluid">
 --> <a class="navbar-brand" href="{% url 'authentication:index' %}">
      <img src="{% static 'authentication/logo.png' %}">
      Wellness Abroad</a>
    <!-- Start Button -->

    <button class="navbar-toggler" type="button " data-toggle="collapse" data-target="#navbarResponsive">
      <span class="navbar-toggler-icon"></span>
    </button>


    <!-- Start Button -->

    <button class="navbar-toggler navbar-toggler-right" type="button " data-toggle="collapse"
      data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- End Button -->

    <!-- Start Links -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <!-- Home -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:index' %}">Home</a>
        </li>

        <!-- About -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:about' %}">About</a>
        </li>

        <!-- Profile -->
        <li class="nav-item">
          <a style="color: white" class="nav-link" href="{% url 'authentication:view_profile' %}">Profile</a>
        </li>

        <!-- Events -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'event:event_index' %}">Events</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
        </li>

      </ul>
    </div>
    <!-- End Links-->


    </div>
    <!-- End Container -->
  </nav>

  <!-- End Navigation -->
  <div style="height: 58px"> </div>
  <!-- Start Contianer -->
  <div class="container" style="margin-left: 100px; margin-right:50px">
    <div style="height:150px"> </div>
    <center>
      <div class="row">
        <div class="col-md-4">
          <img style="width:300px;height:300px; margin-left: 50px" class="img-fluid rounded mb-3 mb-md-0"
            src="{{ user.image.url }}" alt="My Image">
          <div style="height: 10px;"> </div>
          <a style="margin-left: 250px" href="{% url 'authentication:edit_profile_image' %}"> Edit </a>
        </div>
        <div style="width:50px"></div>
        <div class="col-md-4">
          <div class="row">
            <h3 style="color: #073949; font-size:40px">{{user.name}}</h3>
            <a style="margin-left: 5px" href="{% url 'authentication:edit_profile_name' %}"> Edit </a>
          </div>
          <div style="height:10px"> </div>
          <div class="row">
            <h3 style="color: #073949; font-size:25px">{{user.email}}</h3>
            <a style="margin-left: 5px" href="{% url 'authentication:edit_profile_email' %}"> Edit </a>
          </div>
          <div style="height:30px"> </div>
          <div class="row">
            <p style="color: #073949; font-size: 20px"> Age : </p>
            <div style="width: 15px"> </div>
            <p style="color: #073949; font-size: 20px"> {{user.age}}</p>
            <a style="margin-left: 5px" href="{% url 'authentication:edit_profile_age' %}"> Edit </a>
          </div>
          <div class="row">
            <p style="color: #073949; font-size: 20px"> Gender : </p>
            <div style="width: 15px"> </div>
            <p style="color: #073949; font-size: 20px"> {{user.gender}}</p>
            <a style="margin-left: 5px" href="{% url 'authentication:edit_profile_gender' %}"> Edit </a>
          </div>
          <div class="row">
            <p style="color: #073949; font-size: 20px"> Interest : </p>
            <div style="width: 15px"> </div>
            <p style="color: #073949; font-size: 20px"> {{user.interest}}</p>
            <a style="margin-left: 5px" href="{% url 'authentication:edit_profile_interest' %}"> Edit </a>
          </div>
        </div>

      </div>
    </center>
  </div>
  <!--End Container-->

  <br>
  <br>


  <!--  nned to change it so it is stuck into the bottom of the page -->
  <footer class="py-5 bg-dark"
    style="background-color: #073949!important; position:absolute; width: 100%; bottom: -50px; height: 30px">
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>